### PR TITLE
Support SwiftPM (4.1.0)

### PR DESCRIPTION
**Pull request by Nonchalant**
Swift Version of MirrorDiffKit is recognized as **Swift 3.3** when using by SwiftPM.

I understand Syntax of MirrorDiffKit is **Swift 4.1**, but SwiftPM doesn't recognize correctly 😱 

This issue can be resolved by fixing Package.swift to syntax of SwiftPM (4.1.0) 🚀

### CODE REVIEW

**Comment by Kuniwak** [comment]
@Nonchalant Thanks for reporting.

> I understand Syntax of MirrorDiffKit is Swift 4.1

I think MirrorDiffKit still can compile on Swift 3.1 (but I confirmed that compiling tests are failed).

So, we should support Swift 3.1 to make compatibility with Swift 3.x if we can.
Did you test this patch on Swift 3.1? (and I did not confirmed yet)

**Comment by Nonchalant** [comment]
@Kuniwak I confirmed test is successful on Swift 3.3. Is it OK?

```bash
$ swift package --version
// Apple Swift Package Manager - Swift 4.1.0 (swiftpm-14050)

$ swift package generate xcodeproj
// Set swift 3.3 manualy
$ swift test // Successful
```

**Comment by Kuniwak** [comment]
@Nonchalant Hmm... This result seems strange, because some tests are not compatible for Swift 3.

I'm gonna investigate the cause.

**Comment by Kuniwak** [comment]
I'm sorry about my tooooooo late reply.

I decided to merge it, because If any problems are occured, we can fix it. 
Thanks for your contributions!

**Pull request merged**
